### PR TITLE
Cadence 1.0 changes

### PR DESCRIPTION
**Pull request by NtTestAlert**
## Description

quick bandage for cadence 1.0 enforcing scripts to begin with
`access(all) fun main`
instead of
`pub fun main`

which breaks cadut parser, which in turn is used by flow-js-testing

ideally should release a version with a fix for this ASAP, so that flow-js-testing can be fixed without patching

Also updated the templates for contract deploy/update.

---

For contributor use:

- [x] Targeted PR against `master` branch
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [ ] Code follows the [standards mentioned here](https://github.com/onflow/flow-js-testing/blob/master/CONTRIBUTING.md#styleguides)
- [ ] Updated relevant documentation
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Added appropriate labels

### CODE REVIEW

**Review by jribbink — APPROVED** [review]

**Comment by NtTestAlert** [comment]
I've changed the workflow to use Cadence 1.0 CLI
This will need to be reverted later on

**Comment by NtTestAlert** [comment]
Worth noting, the update template handles both update and deploy, but the param deciding which one to use is broken - if you set update to true it will use the deploy-only version. Not touching that to not break compat.

```
  const template = update ? addContractTemplate : updateContractTemplate
```

**Review by jribbink — CHANGES_REQUESTED** [review]
Code looks good -- not really sure about the failing tests/if it's related to this PR or was a pre-existing issue.

The only major thing I see is that it doesn't look like authorized `&Account` references will work with the parser/extracting signers from the prepare block.  I think that this should be fixed in order to ship this - I think it would be an immediate pain point for anybody trying to use this library assuming it has complete Cadence 1.0 support.

(same as https://github.com/onflow/flow-js-testing/pull/225#issuecomment-2021869776)

**Comment by NtTestAlert** [comment]
@jribbink 
The failing tests are related to a plugin library (but they ran locally now so probably related)
Fixed parsing of authorized arguments

**Pull request merged**
